name: liesel-jss
channels:
  - conda-forge
  - nodefaults
dependencies:
  # - blas=*=netlib
  - pip
  - pygraphviz
  - python<3.13
  - quarto
  - r-base
  - r-ggplot2
  - r-knitr
  - r-mgcv
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - pip:
    - liesel<0.4
